//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resources.rc
//
#define ICONDESMUME                     101
#define IDD_RECORDMOVIE                 101
#define IDM_OPEN                        101
#define IDM_QUIT                        102
#define IDC_FERMER                      103
#define IDD_DESASSEMBLEUR_VIEWER7       103
#define IDC_STEP                        104
#define IDC_SETPNUM                     105
#define IDC_SCROLLER                    106
#define IDD_SOUNDSETTINGS               106
#define IDB_FRAMEADVANCE                106
#define IDC_GO                          107
#define IDC_AUTO_UPDATE                 108
#define IDB_OPEN                        108
#define IDM_MEMORY                      109
#define IDC_CONTINUE                    109
#define IDM_DISASSEMBLER                110
#define IDB_PAUSE                       110
#define IDD_3DSETTINGS                  111
#define IDM_GAME_INFO                   111
#define IDB_PLAY                        112
#define IDD_GBASLOT                     113
#define IDM_PAUSE                       113
#define IDD_GBASLOT_CFLASH              114
#define IDM_RESET                       114
#define IDB_RESET                       114
#define IDD_CHEAT_SEARCH_VIEW           115
#define IDM_IOREG                       115
#define IDD_CHEAT_LIST                  116
#define IDB_STOP                        116
#define IDD_CHEAT_ADD                   117
#define IDM_PAL                         117
#define IDM_TILE                        118
#define IDM_MAP                         119
#define IDB_ROTATECCW                   119
#define IDM_MBG0                        120
#define IDB_BITMAP2                     120
#define IDB_ROTATECW                    120
#define IDM_MBG1                        121
#define IDM_MBG2                        122
#define IDD_CHEAT_EXPORT                122
#define IDM_MBG3                        123
#define IDM_SBG0                        124
#define IDM_SBG1                        125
#define IDD_IMPORT_SAVE_SIZE            125
#define IDM_SBG2                        126
#define IDD_SLOT1CONFIG                 126
#define IDM_SBG3                        127
#define IDD_DIALOG1                     127
#define IDM_OAM                         128
#define IDD_TOOL_FSNITRO                128
#define IDR_POPUPM_FSNITRO              128
#define IDM_PRINTSCREEN                 129
#define MENU_FSNITRO                    129
#define IDM_QUICK_PRINTSCREEN           130
#define IDM_SOUNDSETTINGS               131
#define IDD_PROGRESS_WND                131
#define IDM_WEBSITE                     132
#define IDM_FORUM                       133
#define IDM_SUBMITBUGREPORT             134
#define IDM_STATE_LOAD                  135
#define IDM_STATE_SAVE                  136
#define IDI_FOLDER_OPEN                 136
#define IDI_FOLDER_CLOSED               137
#define IDI_FILE_BINARY                 138
#define IDM_STATE_SAVE_F10              139
#define IDM_STATE_SAVE_F1               140
#define IDM_STATE_SAVE_F2               141
#define IDM_STATE_SAVE_F3               142
#define IDM_STATE_SAVE_F4               143
#define IDM_STATE_SAVE_F5               144
#define IDM_STATE_SAVE_F6               145
#define IDM_STATE_SAVE_F7               146
#define IDM_STATE_SAVE_F8               147
#define IDM_STATE_SAVE_F9               148
#define IDM_STATE_LOAD_F10              149
#define IDM_STATE_LOAD_F1               150
#define IDM_STATE_LOAD_F2               151
#define IDM_STATE_LOAD_F3               152
#define IDM_STATE_LOAD_F4               153
#define IDM_STATE_LOAD_F5               154
#define IDM_STATE_LOAD_F6               155
#define IDM_STATE_LOAD_F7               156
#define IDM_STATE_LOAD_F8               157
#define IDM_STATE_LOAD_F9               158
#define IDC_COMBO1                      160
#define IDC_COMBO2                      161
#define IDC_COMBO3                      162
#define IDC_COMBO4                      163
#define IDM_CONFIG                      180
#define IDC_FRAMESKIP0                  191
#define IDC_FRAMESKIP1                  192
#define IDC_FRAMESKIP2                  193
#define IDC_FRAMESKIP3                  194
#define IDC_FRAMESKIP4                  195
#define IDC_FRAMESKIP5                  196
#define IDC_FRAMESKIP6                  197
#define IDC_FRAMESKIP7                  198
#define IDC_FRAMESKIP8                  199
#define IDC_EDIT_FILENAME               200
#define IDC_FRAMESKIP9                  200
#define IDC_BUTTON_BROWSEFILE           201
#define IDC_CHECK_READONLY              201
#define IDM_IMPORTBACKUPMEMORY          201
#define IDM_MGPU                        219
#define IDM_SGPU                        220
#define IDC_FRAMESKIPAUTO               221
#define IDC_8_BIT                       302
#define IDC_16_BIT                      303
#define IDC_32_BIT                      304
#define IDC_BACKGROUNDPAUSE             305
#define IDC_BACKGROUNDINPUT             306
#define IDC_LUACONSOLE                  309
#define IDC_EDIT_LUAPATH                310
#define IDC_BUTTON_LUARUN               311
#define IDC_BUTTON_LUASTOP              312
#define IDC_BUTTON_LUABROWSE            313
#define IDC_BUTTON_LUAEDIT              314
#define IDC_NOTIFY_SUBSERVIENT          315
#define IDD_ARCHIVEFILECHOOSER          316
#define IDD_LUA                         317
#define IDC_NEW_LUA_SCRIPT              318
#define IDC_PATHEDIT                    319
#define IDC_BROWSE                      320
#define IDC_USELASTVISIT                321
#define IDC_FORMATEDIT                  322
#define IDC_PATHLIST                    323
#define IDC_SAVEAS                      324
#define IDC_PNG                         325
#define IDC_BMP                         326
#define IDC_FORMATSTATIC                327
#define IDM_CLOSEROM                    328
#define IDM_PATHSETTINGS                350
#define IDC_ROMPATHEDIT                 351
#define IDC_BROWSEROMS                  352
#define IDC_PATHDEFAULTS                353
#define IDC_SAVERAMPATHEDIT             354
#define IDC_BROWSESRAM                  355
#define IDC_STATEPATHEDIT               356
#define IDC_BROWSESTATES                357
#define IDC_SCREENSHOTPATHEDIT          358
#define IDC_BROWSESCREENSHOTS           359
#define IDC_AVIPATHEDIT                 360
#define IDC_BROWSEAVI                   361
#define IDC_CHEATPATHEDIT               362
#define IDC_BROWSECHEATS                363
#define IDC_LUAPATHEDIT                 364
#define IDC_BROWSELUA                   365
#define IDD_PATHSETTINGS                366
#define IDC_ASSOCIATE                   367
#define IDC_CLOSE_LUA_SCRIPTS           368
#define IDC_SRAMIMPORTPATHEDIT          369
#define IDC_BROWSESRAMIMPORT            370
#define IDC_STATESLOTPATHEDIT           371
#define IDC_BROWSESTATESLOTS            372
#define IDC_DES_BOX                     402
#define IDC_R0                          403
#define IDC_R1                          404
#define IDC_R2                          405
#define IDC_R3                          406
#define IDC_R4                          407
#define IDC_R5                          408
#define IDC_R6                          409
#define IDC_R7                          410
#define IDC_R8                          411
#define IDC_R9                          412
#define IDC_R10                         413
#define IDC_R11                         414
#define IDC_R12                         415
#define IDC_R13                         416
#define IDC_R14                         417
#define IDC_R15                         418
#define IDC_MODE                        419
#define IDC_AUTO_DES                    420
#define IDC_ARM                         421
#define IDC_THUMB                       422
#define IDC_GOTODES                     423
#define IDC_TMP                         424
#define IDD_GAME_INFO                   501
#define ID_RAM_WATCH                    550
#define IDM_RENDER_NORMAL               551
#define IDM_RENDER_HQ2X                 552
#define IDM_RENDER_2XSAI                553
#define IDM_RENDER_SUPER2XSAI           554
#define IDM_RENDER_SUPEREAGLE           555
#define IDM_RENDER_SCANLINE             556
#define IDM_RENDER_BILINEAR             557
#define IDM_RENDER_NEAREST2X            558
#define IDM_RENDER_EPX                  559
#define IDM_RENDER_EPXPLUS              560
#define IDM_RENDER_EPX1POINT5           561
#define IDM_RENDER_EPXPLUS1POINT5       562
#define IDM_RENDER_NEAREST1POINT5       563
#define IDM_RENDER_NEARESTPLUS1POINT5   564
#define IDD_IO_REG                      601
#define IDM_RECORD_MOVIE                602
#define IDM_PLAY_MOVIE                  603
#define IDD_PAL                         703
#define IDD_TILE                        704
#define IDC_PAL_SELECT                  705
#define IDC_PALNUM                      706
#define IDC_MEM_SELECT                  707
#define IDC_Tile_BOX                    708
#define IDC_BITMAP                      709
#define IDC_256COUL                     710
#define IDC_16COUL                      711
#define IDC_MINI_TILE                   712
#define IDC_TILENUM                     713
#define IDD_MAP                         800
#define IDC_BG_SELECT                   801
#define IDC_PAL                         803
#define IDC_PRIO                        804
#define IDC_CHAR                        805
#define IDC_SCR                         806
#define IDC_MSIZE                       807
#define IDC_SCROLL                      808
#define IDD_OAM                         900
#define IDC_SCR_SELECT                  901
#define IDC_TILE                        902
#define IDC_OAMNUM                      903
#define IDC_COOR                        904
#define IDC_DIM                         905
#define IDC_ROT                         906
#define IDC_MOS                         907
#define IDC_PROP0                       908
#define IDC_PROP1                       909
#define IDD_EMULATIONSETTINGS           916
#define IDD_WIFISETTINGS                918
#define IDD_MEM_VIEW                    920
#define IDC_DIFFERENTFROM               921
#define IDC_DIFFERENTBY                 922
#define IDC_MODULO                      923
#define IDC_EDIT_DIFFBY                 924
#define IDC_EDIT_MODBY                  925
#define IDC_PREVIOUSVALUE               926
#define IDC_SPECIFICVALUE               927
#define IDC_NUMBEROFCHANGES             928
#define IDC_EDIT_COMPAREVALUE           929
#define IDC_EDIT_COMPARECHANGES         930
#define IDC_C_AUTOSEARCH                931
#define IDC_MISALIGN                    932
#define IDC_C_RESET_CHANGES             933
#define IDC_C_UNDO                      934
#define ID_RAM_SEARCH                   935
#define IDD_RAMSEARCH                   945
#define IDC_SPECIFICADDRESS             950
#define IDC_EDIT_COMPAREADDRESS         951
#define IDC_PROMPT_TEXT                 952
#define IDC_PROMPT_EDIT                 953
#define IDC_SIGNED                      954
#define IDC_UNSIGNED                    955
#define IDC_HEX                         956
#define IDC_1_BYTE                      957
#define IDC_2_BYTES                     958
#define IDC_4_BYTES                     959
#define IDC_WATCHLIST                   960
#define IDC_HEX2                        960
#define IDC_C_WATCH_EDIT                961
#define IDC_C_WATCH_REMOVE              962
#define IDC_C_WATCH                     963
#define IDC_C_WATCH_DUPLICATE           964
#define IDC_C_ADDCHEAT                  965
#define ID_WATCHES_UPDOWN               966
#define IDD_RAMWATCH                    967
#define IDC_C_WATCH_DUPLICATE2          967
#define IDC_C_WATCH_SEPARATE            967
#define IDR_ACCELERATOR1                968
#define IDD_PROMPT                      969
#define ID_VIEW_DISPLAYGRAPHICALINPUT   971
#define IDD_SOUND_VIEW                  977
#define IDC_START_FROM_SRAM             978
#define IDC_EDIT_SRAMFILENAME           979
#define IDC_BUTTON_BROWSESRAM           980
#define IDC_C_WATCH_UP                  980
#define IDD_EDITWATCH                   980
#define IDC_START_FROM_POWER_ON         981
#define IDC_C_WATCH_DOWN                981
#define RAMMENU_FILE_AUTOLOAD           982
#define RAMMENU_FILE_SAVEWINDOW         983
#define RAMMENU_FILE_SAVE               984
#define RAMMENU_FILE_SAVEAS             985
#define RAMMENU_FILE_OPEN               986
#define RAMMENU_FILE_APPEND             987
#define RAMMENU_FILE_NEW                988
#define RAMMENU_FILE_RECENT             990
#define IDC_RAMLIST                     991
#define IDC_C_SEARCH                    992
#define IDC_C_RESET                     993
#define IDC_C_ELIMINATE                 994
#define IDC_LESSTHAN                    995
#define IDC_MORETHAN                    996
#define IDC_NOMORETHAN                  997
#define IDC_NOLESSTHAN                  998
#define IDC_EQUALTO                     999
#define IDC_BRIDGEADAPTER               1000
#define IDC_SOUNDCORECB                 1000
#define IDC_USEEXTBIOS                  1000
#define ID_BROWSE                       1000
#define IDC_CHECKBOX_DEBUGGERMODE       1001
#define IDC_SOUNDBUFFERET               1001
#define IDC_SOUNDVIEW_CHANSWITCH        1001
#define PM_FILENAME                     1001
#define IDC_ARM9BIOS                    1002
#define IDC_MLENGTH                     1002
#define IDC_SLVOLUME                    1002
#define IDC_GI_GAMETITLE                1003
#define IDC_MFRAMES                     1003
#define IDC_ROTATE0                     1003
#define IDC_BUTTON2                     1003
#define IDC_CHECKBOX_ENSATAEMULATION    1003
#define IDC_ARM9BIOSBROWSE              1004
#define IDC_GI_GAMECODE                 1004
#define IDC_MRERECORDCOUNT              1004
#define IDC_ROTATE90                    1004
#define IDC_SPU_INTERPOLATION_CB        1004
#define IDC_BUTTON_VOLMODE              1004
#define IDC_ARM7BIOS                    1005
#define IDC_MROM                        1005
#define IDC_ROTATE180                   1005
#define IDC_GGREEN                      1005
#define IDC_ROTATE270                   1006
#define IDC_GRED                        1006
#define IDC_ARM7BIOSBROWSE              1007
#define IDC_GYELLOW                     1007
#define IDC_MEMVIEWBOX                  1008
#define IDC_GBLUE                       1008
#define IDC_ADHOC_SERVER                1008
#define IDC_ADDRESS                     1009
#define IDC_BIOSSWIS                    1009
#define IDC_FORCERATIO                  1009
#define IDC_ADHOC_CLIENT                1009
#define IDC_AUTO_UPDATE_SPIN            1010
#define IDC_TEXTDUMP                    1010
#define IDC_WINDOW1X                    1010
#define IDC_ADHOC_SERVERNAME            1010
#define IDC_AUTO_UPDATE_SECS            1011
#define IDC_USEEXTFIRMWARE              1011
#define IDC_WINDOW2X                    1011
#define IDC_FIRMWARE                    1012
#define IDC_RAWDUMP                     1012
#define IDC_REFRESH                     1012
#define IDC_WINDOW3X                    1012
#define IDC_SYNCHMODE_DUAL              1012
#define IDC_WINDOW4X                    1013
#define IDC_VIEWMODE                    1013
#define IDC_SYNCHMODE_SYNCH             1013
#define IDC_FIRMWAREBROWSE              1014
#define IDC_VOLUME                      1014
#define IDC_DUMPALL                     1014
#define IDC_SYNCHMETHOD_N               1015
#define IDC_FIRMWAREBOOT                1016
#define IDC_SYNCHMETHOD_Z               1016
#define IDC_GROUP_SYNCHMETHOD           1017
#define IDC_AUTOUPDATE_ASM              1018
#define IDC_SYNCHMETHOD_P               1018
#define IDC_VISIBLE                     1019
#define IDC_USEPHYSICAL                 1019
#define IDC_SPLIT1                      1021
#define IDC_PATCHSWI3                   1022
#define IDC_CAP0_ADD                    1023
#define IDC_CAP0_CURDAD                 1024
#define IDC_CAP1_ADD                    1025
#define IDC_SPU_ADVANCED                1025
#define IDC_CAP1_CURDAD                 1026
#define IDC_CHECBOX_ADVANCEDTIMING      1026
#define IDC_DEFAULT                     1027
#define IDC_DTP_DATE                    1027
#define IDC_3DCORE                      1028
#define IDC_SNDCTRL_ENABLE              1028
#define IDC_DTP_TIME                    1028
#define IDC_CHECKBOX_GAMEHACKS          1028
#define IDC_TXT_COMPILED                1029
#define IDC_SNDCTRL_CH1NOMIX            1029
#define IDC_DTP_DATE2                   1029
#define IDC_TXT_VERSION                 1030
#define IDC_SNDCTRL_CH3NOMIX            1030
#define IDC_DTP_TIME2                   1030
#define IDC_SOUND_CAPTURE_MUTED         1031
#define IDC_SOUND_ANALYZE_CAP           1032
#define IDC_ADDONS_LIST                 1033
#define IDC_BUTTON3                     1033
#define IDC_SOUND_UNMUTE_ALL            1033
#define IDC_PIANO_C                     1033
#define IDC_ADDONS_INFO                 1034
#define IDC_BORDER                      1034
#define IDC_PIANO_CS                    1034
#define IDC_BBROWSE                     1035
#define IDC_PIANO_D                     1035
#define IDC_ADDONS_INFO2                1035
#define IDC_PATHIMG                     1036
#define IDC_PIANO_DS                    1036
#define IDC_ADDONS_INFO3                1036
#define IDC_PATH                        1037
#define IDC_PATHGAME                    1037
#define IDC_PIANO_E                     1037
#define IDC_LIST_CHEATS                 1037
#define IDC_RFILE                       1038
#define IDC_EXPORT                      1038
#define IDC_RFOLDER                     1039
#define IDC_2012                        1039
#define IDC_EXPORT2                     1039
#define IDC_BBROWSE2                    1040
#define IDC_PATHDESMUME                 1041
#define IDC_CDATE                       1041
#define IDC_BRESTART                    1042
#define IDC_BVIEW                       1043
#define IDC_R4TYPE1                     1043
#define IDC_BSEARCH                     1044
#define IDC_PIANO_F                     1044
#define IDC_R4TYPE2                     1044
#define IDC_RADIO1                      1045
#define IDC_PIANO_FS                    1045
#define IDC_RADIO2                      1046
#define IDC_PIANO_GS                    1046
#define IDC_RADIO3                      1047
#define IDC_PIANO_B                     1047
#define IDC_RADIO4                      1048
#define IDC_PIANO_A                     1048
#define IDC_RADIO5                      1049
#define IDC_PIANO_AS                    1049
#define IDC_AR_CODE                     1049
#define IDC_RADIO6                      1050
#define IDC_PIANO_G                     1050
#define IDC_RADIO7                      1051
#define IDC_PIANO_DS3                   1051
#define IDC_PIANO_HIC                   1051
#define IDC_CHECKBOX_DYNAREC            1052
#define IDC_RADIO8                      1052
#define IDC_IMP_AUTO_CURRENT            1052
#define IDC_USE_STDOUT                  1052
#define IDC_IMP_AUTO_FILE               1053
#define IDC_BUTTON1                     1053
#define IDC_IMP_AUTO_ADVANSCENE         1054
#define IDC_JIT_BLOCK_SIZE              1054
#define IDC_SDEVELOPER                  1054
#define IDC_CURRENT_ADDR                1054
#define IDC_IMP_MANUAL                  1055
#define IDC_FULL_CHARS                  1055
#define IDC_LIST1                       1056
#define IDC_IMP_INFO_CURRENT            1056
#define IDC_FIRMWAREEXTUSER             1056
#define IDC_DIRECTORY_SCAN              1056
#define IDC_BADD_AR                     1057
#define IDC_IMP_INFO_FILE               1057
#define IDC_FILES_TREE                  1057
#define IDC_PROGRESS_BAR                1057
#define IDC_PINC                        1057
#define IDC_BADD_CB                     1058
#define IDC_IMP_INFO_ADVANSCENE         1058
#define IDC_FILE_INFO                   1058
#define IDC_MESSAGE                     1058
#define IDC_PDEC                        1058
#define IDC_IMP_MANUAL_SIZE             1059
#define IDC_BREMOVE                     1060
#define IDC_FILE_QVIEW                  1060
#define IDC_BEDIT                       1061
#define IDC_STATIC_S1                   1061
#define IDC_SPIN1                       1061
#define IDC_NUD_PRESCALEHD              1061
#define IDC_STATIC_S2                   1062
#define IDC_TEXT_PRESCALEHD             1062
#define IDC_STATIC_S3                   1063
#define IDC_STATIC_S4                   1064
#define IDC_EVALUE                      1065
#define IDC_WIFI_ENABLED                1065
#define IDC_STATIC_RANGE                1066
#define IDC_WIFI_COMPAT                 1066
#define IDC_TEXSCALE                    1067
#define IDC_BADD                        1068
#define IDC_LIST                        1069
#define IDC_TEX_DEPOSTERIZE             1070
#define IDC_SNUMBER                     1071
#define IDC_TEX_SMOOTH                  1072
#define IDC_CHECK1                      1074
#define IDC_CHECK2                      1075
#define IDC_CAP0_SRC                    1075
#define IDC_CHECK3                      1076
#define IDC_CAP0_ONESHOT                1076
#define IDC_CHECK4                      1077
#define IDC_CAP0_TYPE                   1077
#define IDC_CAP0_ACTIVE                 1078
#define IDC_CHECK10                     1079
#define IDC_CAP0_RUNNING                1079
#define IDC_BIG_ENDIAN                  1079
#define IDC_CHECK6                      1080
#define IDC_CAP1_SRC                    1080
#define IDC_CAP1_ONESHOT                1081
#define IDC_CHECK7                      1082
#define IDC_CAP1_TYPE                   1082
#define IDC_CHECK8                      1083
#define IDC_CAP1_ACTIVE                 1083
#define IDC_CAP1_RUNNING                1084
#define IDC_CHECK9                      1088
#define IDC_S2X                         1090
#define IDC_S4X                         1091
#define IDC_S8X                         1092
#define IDC_S16X                        1093
#define IDC_MULTISAMPLE_SIZE            1094
#define IDC_GPU_COLOR_DEPTH             1095
#define IDC_SHADOW_POLYGONS             1096
#define IDC_S_0_ALPHA_BLEND             1097
#define IDC_NDS_DEPTH_CALC              1098
#define IDC_DEPTH_L_EQUAL_PF            1099
#define IDM_FIRMSETTINGS                1100
#define IDD_FIRMSETTINGS                1101
#define IDC_EDIT1                       1102
#define IDC_EDIT2                       1103
#define IDC_EDIT3                       1104
#define IDC_WINDOW5X                    1105
#define IDC_EDIT_AUTHOR                 1180
#define IDD_MATRIX_VIEWER               1200
#define IDM_MATRIX_VIEWER               1200
#define IDC_MATRIX_VIEWER_COORD_GROUP   1201
#define IDC_MATRIX_VIEWER_COORD_COMBO   1202
#define IDC_MATRIX_VIEWER_COORD_11_EDIT 1203
#define IDC_MATRIX_VIEWER_COORD_12_EDIT 1204
#define IDC_MATRIX_VIEWER_COORD_13_EDIT 1205
#define IDC_MATRIX_VIEWER_COORD_14_EDIT 1206
#define IDC_MATRIX_VIEWER_COORD_21_EDIT 1207
#define IDC_MATRIX_VIEWER_COORD_22_EDIT 1208
#define IDC_MATRIX_VIEWER_COORD_23_EDIT 1209
#define IDC_MATRIX_VIEWER_COORD_24_EDIT 1210
#define IDC_MATRIX_VIEWER_COORD_31_EDIT 1211
#define IDC_MATRIX_VIEWER_COORD_32_EDIT 1212
#define IDC_MATRIX_VIEWER_COORD_33_EDIT 1213
#define IDC_MATRIX_VIEWER_COORD_34_EDIT 1214
#define IDC_MATRIX_VIEWER_COORD_41_EDIT 1215
#define IDC_MATRIX_VIEWER_COORD_42_EDIT 1216
#define IDC_MATRIX_VIEWER_COORD_43_EDIT 1217
#define IDC_MATRIX_VIEWER_COORD_44_EDIT 1218
#define IDC_MATRIX_VIEWER_DIR_GROUP     1221
#define IDC_MATRIX_VIEWER_DIR_COMBO     1222
#define IDC_MATRIX_VIEWER_DIR_11_EDIT   1223
#define IDC_MATRIX_VIEWER_DIR_12_EDIT   1224
#define IDC_MATRIX_VIEWER_DIR_13_EDIT   1225
#define IDC_MATRIX_VIEWER_DIR_14_EDIT   1226
#define IDC_MATRIX_VIEWER_DIR_21_EDIT   1227
#define IDC_MATRIX_VIEWER_DIR_22_EDIT   1228
#define IDC_MATRIX_VIEWER_DIR_23_EDIT   1229
#define IDC_MATRIX_VIEWER_DIR_24_EDIT   1230
#define IDC_MATRIX_VIEWER_DIR_31_EDIT   1231
#define IDC_MATRIX_VIEWER_DIR_32_EDIT   1232
#define IDC_MATRIX_VIEWER_DIR_33_EDIT   1233
#define IDC_MATRIX_VIEWER_DIR_34_EDIT   1234
#define IDC_MATRIX_VIEWER_DIR_41_EDIT   1235
#define IDC_MATRIX_VIEWER_DIR_42_EDIT   1236
#define IDC_MATRIX_VIEWER_DIR_43_EDIT   1237
#define IDC_MATRIX_VIEWER_DIR_44_EDIT   1238
#define IDC_MATRIX_VIEWER_PROJ_GROUP    1241
#define IDC_MATRIX_VIEWER_PROJ_11_EDIT  1243
#define IDC_MATRIX_VIEWER_PROJ_12_EDIT  1244
#define IDC_MATRIX_VIEWER_PROJ_13_EDIT  1245
#define IDC_MATRIX_VIEWER_PROJ_14_EDIT  1246
#define IDC_MATRIX_VIEWER_PROJ_21_EDIT  1247
#define IDC_MATRIX_VIEWER_PROJ_22_EDIT  1248
#define IDC_MATRIX_VIEWER_PROJ_23_EDIT  1249
#define IDC_MATRIX_VIEWER_PROJ_24_EDIT  1250
#define IDC_MATRIX_VIEWER_PROJ_31_EDIT  1251
#define IDC_MATRIX_VIEWER_PROJ_32_EDIT  1252
#define IDC_MATRIX_VIEWER_PROJ_33_EDIT  1253
#define IDC_MATRIX_VIEWER_PROJ_34_EDIT  1254
#define IDC_MATRIX_VIEWER_PROJ_41_EDIT  1255
#define IDC_MATRIX_VIEWER_PROJ_42_EDIT  1256
#define IDC_MATRIX_VIEWER_PROJ_43_EDIT  1257
#define IDC_MATRIX_VIEWER_PROJ_44_EDIT  1258
#define IDC_MATRIX_VIEWER_TEX_GROUP     1261
#define IDC_MATRIX_VIEWER_TEX_11_EDIT   1263
#define IDC_MATRIX_VIEWER_TEX_12_EDIT   1264
#define IDC_MATRIX_VIEWER_TEX_13_EDIT   1265
#define IDC_MATRIX_VIEWER_TEX_14_EDIT   1266
#define IDC_MATRIX_VIEWER_TEX_21_EDIT   1267
#define IDC_MATRIX_VIEWER_TEX_22_EDIT   1268
#define IDC_MATRIX_VIEWER_TEX_23_EDIT   1269
#define IDC_MATRIX_VIEWER_TEX_24_EDIT   1270
#define IDC_MATRIX_VIEWER_TEX_31_EDIT   1271
#define IDC_MATRIX_VIEWER_TEX_32_EDIT   1272
#define IDC_MATRIX_VIEWER_TEX_33_EDIT   1273
#define IDC_MATRIX_VIEWER_TEX_34_EDIT   1274
#define IDC_MATRIX_VIEWER_TEX_41_EDIT   1275
#define IDC_MATRIX_VIEWER_TEX_42_EDIT   1276
#define IDC_MATRIX_VIEWER_TEX_43_EDIT   1277
#define IDC_MATRIX_VIEWER_TEX_44_EDIT   1278
#define IDD_LIGHT_VIEWER                1300
#define IDM_LIGHT_VIEWER                1300
#define IDC_LIGHT_VIWER_LIGHT0_GROUP    1301
#define IDD_ABOUT_BOX                   1301
#define IDC_AUTHORS_LIST                1302
#define IDC_LIGHT_VIEWER_LIGHT0COLOR_COLORCTRL 1302
#define IDD_DESASSEMBLEUR_VIEWER9       1302
#define IDC_LIGHT_VIEWER_LIGHT0COLOR_EDIT 1303
#define IDC_LIGHT_VIEWER_LIGHT0VECTOR_EDIT 1304
#define IDD_GBASLOT_NONE                1304
#define IDD_GBASLOT_RUMBLEPAK           1305
#define IDD_GBASLOT_GBAGAME             1306
#define IDD_CHEAT_SEARCH_COMP           1307
#define IDD_CHEAT_SEARCH_MAIN           1308
#define IDD_CHEAT_SEARCH_RESULT         1310
#define IDC_LIGHT_VIWER_LIGHT1_GROUP    1311
#define IDD_CHEAT_SEARCH_EXACT          1311
#define IDC_LIGHT_VIEWER_LIGHT1COLOR_COLORCTRL 1312
#define IDD_CHEAT_SEARCH                1312
#define IDC_LIGHT_VIEWER_LIGHT1COLOR_EDIT 1313
#define IDC_LIGHT_VIEWER_LIGHT1VECTOR_EDIT 1314
#define IDC_LIGHT_VIWER_LIGHT2_GROUP    1321
#define IDC_LIGHT_VIEWER_LIGHT2COLOR_COLORCTRL 1322
#define IDC_LIGHT_VIEWER_LIGHT2COLOR_EDIT 1323
#define IDC_LIGHT_VIEWER_LIGHT2VECTOR_EDIT 1324
#define IDC_LIGHT_VIWER_LIGHT3_GROUP    1331
#define IDC_LIGHT_VIEWER_LIGHT3COLOR_COLORCTRL 1332
#define IDC_LIGHT_VIEWER_LIGHT3COLOR_EDIT 1333
#define IDC_LIGHT_VIEWER_LIGHT3VECTOR_EDIT 1334
#define IDC_SOUND0ID                    1350
#define IDC_SOUND1ID                    1351
#define IDC_SOUND2ID                    1352
#define IDC_SOUND3ID                    1353
#define IDC_SOUND4ID                    1354
#define IDC_SOUND5ID                    1355
#define IDC_SOUND6ID                    1356
#define IDC_SOUND7ID                    1357
#define IDC_SOUND0VOL                   1358
#define IDC_SOUND1VOL                   1359
#define IDC_SOUND2VOL                   1360
#define IDC_SOUND3VOL                   1361
#define IDC_SOUND4VOL                   1362
#define IDC_SOUND5VOL                   1363
#define IDC_SOUND6VOL                   1364
#define IDC_SOUND7VOL                   1365
#define IDC_SOUND0VOLBAR                1366
#define IDC_SOUND1VOLBAR                1367
#define IDC_SOUND2VOLBAR                1368
#define IDC_SOUND3VOLBAR                1369
#define IDC_SOUND4VOLBAR                1370
#define IDC_SOUND5VOLBAR                1371
#define IDC_SOUND6VOLBAR                1372
#define IDC_SOUND7VOLBAR                1373
#define IDC_SOUND0PAN                   1374
#define IDC_SOUND1PAN                   1375
#define IDC_SOUND2PAN                   1376
#define IDC_SOUND3PAN                   1377
#define IDC_SOUND4PAN                   1378
#define IDC_SOUND5PAN                   1379
#define IDC_SOUND6PAN                   1380
#define IDC_SOUND7PAN                   1381
#define IDC_SOUND0PANBAR                1382
#define IDC_SOUND1PANBAR                1383
#define IDC_SOUND2PANBAR                1384
#define IDC_SOUND3PANBAR                1385
#define IDC_SOUND4PANBAR                1386
#define IDC_SOUND5PANBAR                1387
#define IDC_SOUND6PANBAR                1388
#define IDC_SOUND7PANBAR                1389
#define IDC_SOUND0HOLD                  1390
#define IDC_SOUND1HOLD                  1391
#define IDC_SOUND2HOLD                  1392
#define IDC_SOUND3HOLD                  1393
#define IDC_SOUND4HOLD                  1394
#define IDC_SOUND5HOLD                  1395
#define IDC_SOUND6HOLD                  1396
#define IDC_SOUND7HOLD                  1397
#define IDC_SOUND0BUSY                  1398
#define IDC_SOUND1BUSY                  1399
#define IDC_SOUND2BUSY                  1400
#define IDC_SOUND3BUSY                  1401
#define IDC_SOUND4BUSY                  1402
#define IDC_SOUND5BUSY                  1403
#define IDC_SOUND6BUSY                  1404
#define IDC_SOUND7BUSY                  1405
#define IDC_SOUND0REPEATMODE            1406
#define IDC_SOUND1REPEATMODE            1407
#define IDC_SOUND2REPEATMODE            1408
#define IDC_SOUND3REPEATMODE            1409
#define IDC_SOUND4REPEATMODE            1410
#define IDC_SOUND5REPEATMODE            1411
#define IDC_SOUND6REPEATMODE            1412
#define IDC_SOUND7REPEATMODE            1413
#define IDC_SOUND0FORMAT                1414
#define IDC_SOUND1FORMAT                1415
#define IDC_SOUND2FORMAT                1416
#define IDC_SOUND3FORMAT                1417
#define IDC_SOUND4FORMAT                1418
#define IDC_SOUND5FORMAT                1419
#define IDC_SOUND6FORMAT                1420
#define IDC_SOUND7FORMAT                1421
#define IDC_SOUND0SAD                   1422
#define IDC_SOUND1SAD                   1423
#define IDC_SOUND2SAD                   1424
#define IDC_SOUND3SAD                   1425
#define IDC_SOUND4SAD                   1426
#define IDC_SOUND5SAD                   1427
#define IDC_SOUND6SAD                   1428
#define IDC_SOUND7SAD                   1429
#define IDC_SOUND0PNT                   1430
#define IDC_SOUND1PNT                   1431
#define IDC_SOUND2PNT                   1432
#define IDC_SOUND3PNT                   1433
#define IDC_SOUND4PNT                   1434
#define IDC_SOUND5PNT                   1435
#define IDC_SOUND6PNT                   1436
#define IDC_SOUND7PNT                   1437
#define IDC_SOUND0TMR                   1438
#define IDC_SOUND1TMR                   1439
#define IDC_SOUND2TMR                   1440
#define IDC_SOUND3TMR                   1441
#define IDC_SOUND4TMR                   1442
#define IDC_SOUND5TMR                   1443
#define IDC_SOUND6TMR                   1444
#define IDC_SOUND7TMR                   1445
#define IDC_SOUND0POSLEN                1446
#define IDC_SOUND1POSLEN                1447
#define IDC_SOUND2POSLEN                1448
#define IDC_SOUND3POSLEN                1449
#define IDC_SOUND4POSLEN                1450
#define IDC_SOUND5POSLEN                1451
#define IDC_SOUND6POSLEN                1452
#define IDC_SOUND7POSLEN                1453
#define IDC_CAP0_DAD                    1454
#define IDC_CAP0_CTRL                   1455
#define IDC_CAP0_SRCTEXT                1456
#define IDC_CAP0_TYPETEXT               1457
#define IDC_CAP0_LEN                    1458
#define IDC_SOUND0POSLEN7               1459
#define IDC_CAP1_DAD                    1459
#define IDC_CAP1_CTRL                   1460
#define IDC_CAP1_SRCTEXT                1461
#define IDC_CAP1_TYPETEXT               1462
#define IDC_CAP1_LEN                    1463
#define IDC_SNDCTRL_CTRL                1464
#define IDC_SNDCTRL_VOL                 1465
#define IDC_SNDCTRL_BIAS                1466
#define IDC_SNDCTRL_LEFTOUT             1467
#define IDC_SNDCTRL_LEFTOUTTEXT         1468
#define IDC_SNDCTRL_RIGHTOUT            1469
#define IDC_SNDCTRL_RIGHTOUTTEXT        1470
#define IDM_CONSOLE_ALWAYS_ON_TOP       1500
#define IDC_SOUND0MUTE                  2001
#define IDC_SOUND1MUTE                  2002
#define IDC_SOUND2MUTE                  2003
#define IDC_SOUND3MUTE                  2004
#define IDC_SOUND4MUTE                  2005
#define IDC_SOUND5MUTE                  2006
#define IDC_SOUND6MUTE                  2007
#define IDC_SOUND7MUTE                  2008
#define IDD_REPLAYINP                   2010
#define IDD_REPLAY_METADATA             2011
#define MENU_PRINCIPAL                  2012
#define RAMWATCH_MENU                   2013
#define RECENTROMS                      2014
#define IDD_FONTSETTINGS                2464
#define IDC_FONTCOMBO                   2465
#define IDC_GI_FATOFS                   4464
#define IDC_INTERPOLATECOLOR            4464
#define IDC_GI_FATSIZE                  4465
#define IDC_3DSETTINGS_EDGEMARK         4465
#define ID_LABEL_HK1                    4465
#define IDC_GI_ICONTITLEOFS             4466
#define IDC_3DSETTINGS_FOG              4466
#define ID_LABEL_HK2                    4466
#define IDC_GI_USEDROMSIZE              4467
#define ID_LABEL_HK3                    4467
#define IDC_3DSETTINGS_FOG2             4467
#define IDC_3DSETTINGS_TEXTURE          4467
#define ID_LABEL_HK4                    4468
#define IDC_GI_ICON                     4469
#define ID_LABEL_HK5                    4469
#define IDC_3DSETTINGS_LINEHACK         4469
#define IDC_GI_TITLE                    4470
#define ID_LABEL_HK6                    4470
#define IDC_GI_TITLEEN                  4471
#define ID_LABEL_HK7                    4471
#define IDC_GI_TITLEFR                  4472
#define ID_LABEL_HK8                    4472
#define IDC_GI_TITLEGE                  4473
#define ID_LABEL_HK9                    4473
#define IDC_GI_TITLEIT                  4474
#define ID_LABEL_HK10                   4474
#define IDC_GI_TITLESP                  4475
#define ID_LABEL_HK11                   4475
#define IDC_GI_MAKERCODE                4476
#define ID_LABEL_HK12                   4476
#define IDC_GI_TITLEJP                  4477
#define ID_LABEL_HK13                   4477
#define IDC_GI_CHIPSIZE                 4478
#define ID_LABEL_HK14                   4478
#define IDC_GI_ARM9START                4479
#define ID_LABEL_HK15                   4479
#define IDC_GI_ARM9ENTRY                4480
#define ID_LABEL_HK16                   4480
#define IDC_GI_ARM9ROM                  4481
#define ID_LABEL_HK17                   4481
#define IDC_GI_ARM9SIZE                 4482
#define ID_LABEL_HK18                   4482
#define IDC_GI_ARM7ROM                  4483
#define ID_LABEL_HK19                   4483
#define IDC_GI_ARM7ENTRY                4484
#define ID_LABEL_HK20                   4484
#define IDC_GI_ARM7START                4485
#define ID_LABEL_HK21                   4485
#define IDC_GI_ARM7SIZE                 4486
#define ID_LABEL_HK22                   4486
#define IDC_GI_FNTOFS                   4487
#define ID_LABEL_HK23                   4487
#define IDC_GI_FNTSIZE                  4488
#define ID_LABEL_HK24                   4488
#define ID_LABEL_HK25                   4489
#define ID_LABEL_HK26                   4490
#define ID_LABEL_HK27                   4491
#define ID_LABEL_HK28                   4492
#define ID_LABEL_HK29                   4493
#define ID_LABEL_HK30                   4494
#define ID_LABEL_HK31                   4495
#define ID_LABEL_HK32                   4496
#define ID_LABEL_HK33                   4497
#define ID_LABEL_HK34                   4498
#define ID_LABEL_HK35                   4499
#define ID_LABEL_HK36                   4500
#define ID_LABEL_HK37                   4501
#define ID_LABEL_HK38                   4502
#define ID_LABEL_HK39                   4503
#define ID_LABEL_HK40                   4504
#define ID_LABEL_HK41                   4505
#define ID_LABEL_HK42                   4506
#define ID_LABEL_HK43                   4507
#define ID_LABEL_HK44                   4508
#define ID_LABEL_HK45                   4509
#define ID_LABEL_HK46                   4510
#define ID_LABEL_HK47                   4511
#define ID_LABEL_HK48                   4512
#define ID_LABEL_HK49                   4513
#define ID_LABEL_HK50                   4514
#define ID_LABEL_HK51                   4515
#define ID_LABEL_HK52                   4516
#define ID_LABEL_HK53                   4517
#define ID_LABEL_HK13b                  4518
#define ID_LABEL_HK54                   4519
#define ID_LABEL_HK55                   4520
#define ID_LABEL_HK56                   4521
#define ID_LABEL_HK57                   4522
#define ID_LABEL_HK58                   4523
#define ID_LABEL_HK59                   4524
#define ID_LABEL_HK60                   4525
#define ID_LABEL_HK61                   4526
#define ID_LABEL_HK62                   4527
#define ID_LABEL_HK63                   4528
#define ID_LABEL_HK64                   4529
#define ID_LABEL_HK65                   4530
#define ID_LABEL_HK66                   4531
#define ID_LABEL_HK67                   4532
#define ID_LABEL_HK68                   4533
#define ID_LABEL_HK69                   4534
#define ID_LABEL_HK70                   4535
#define ID_LABEL_HK71                   4536
#define ID_LABEL_HK72                   4537
#define ID_LABEL_HK73                   4538
#define ID_LABEL_HK74                   4539
#define ID_LABEL_HK75                   4540
#define ID_LABEL_HK76                   4541
#define IDD_MICROPHONE                  5000
#define IDM_MICROPHONESETTINGS          5001
#define IDC_MICSAMPLEBROWSE             5003
#define IDC_MICSAMPLE                   5004
#define IDC_USEMICSAMPLE                5005
#define IDC_USEMICRAND                  5009
#define IDC_USENOISE                    5010
#define IDC_REGION                      6000
#define IDC_IOREG                       6001
#define IDC_CPU                         6002
#define IDC_R4_FOLDER                   6003
#define IDC_R4_ROM                      6004
#define ID_LABEL_ZELDA_SHADOW_DEPTH_HACK2 9003
#define IDD_CHEAT_ADD_XX_CODE           10005
#define IDD_GBASLOT_GUITARGRIP          10009
#define IDD_GBASLOT_PIANO               10010
#define IDD_SLOT1_NONE                  10011
#define IDD_SLOT1_R4                    10012
#define IDD_SLOT1_DEBUG                 10013
#define IDD_GBASLOT_PADDLE              10014
#define IDM_FILE_STOPAVI                40000
#define IDM_SCREENSEP_NONE              40000
#define IDM_FILE_STOPWAV                40001
#define IDM_SCREENSEP_BORDER            40001
#define IDM_SCREENSEP_NDSGAP            40002
#define IDM_ABOUT                       40003
#define IDM_EMULATIONSETTINGS           40004
#define IDC_FRAMELIMIT                  40005
#define ID_CONFIG_PAUSEWHENFOCUSLOST    40005
#define IDC_WINDOW1_5X                  40006
#define IDM_WIFISETTINGS                40007
#define IDM_ALWAYS_ON_TOP               40008
#define ID_VIEW_FRAMECOUNTER            40009
#define ID_VIEW_DISPLAYFPS              40010
#define ID_VIEW_DISPLAYINPUT            40011
#define ID_VIEW_DISPLAYLAG              40012
#define ID_VIEW_HUDEDITOR               40013
#define ID_VIEW_DISPLAYMICROPHONE       40014
#define IDM_FILE_RECORDAVI              40015
#define IDM_SOUND_VIEW                  40016
#define IDM_FILE_RECORDWAV              40017
#define IDM_EXPORTBACKUPMEMORY          40018
#define IDM_STOPMOVIE                   40019
#define IDM_SCREENSEP_NDSGAP2           40021
#define IDM_SCREENSEP_DRAGEDIT          40022
#define IDM_SCREENSEP_COLORWHITE        40023
#define IDM_SCREENSEP_COLORGRAY         40024
#define IDM_SCREENSEP_COLORBLACK        40025
#define IDM_FILE_RECORDUSERSPUWAV       40026
#define ID_FILE_RECENTROM               40034
#define IDM_DEFSIZE                     40038
#define IDM_3DCONFIG                    40040
#define IDM_GBASLOT                     40042
#define IDM_CHEATS_LIST                 40050
#define IDM_SHUT_UP                     40053
#define IDC_WINDOW2_5X                  40054
#define ID_LCDS_VERTICAL                40055
#define ID_LCDS_HORIZONTAL              40056
#define ID_LCDS_ONE                     40057
#define ID_LCDS_SWAP                    40058
#define ID_LCDS_NOSWAP                  40059
#define ID_LCDS_MAINGPU                 40060
#define ID_LCDS_SUBGPU                  40061
#define IDM_CHEATS_DISABLE              40062
#define IDM_CHEATS_SEARCH               40063
#define IDM_LOCKDOWN                    40066
#define IDM_SHOWTOOLBAR                 40069
#define ID_CONFIG_DISPLAYMETHOD         40070
#define ID_DISPLAYMETHOD_DIRECTDRAWHW   40071
#define ID_DISPLAYMETHOD_DIRECTDRAWSW   40072
#define ID_HOTKEYS_TITLE                40073
#define ID_VIEWLAYERS_SUBOBJ            40074
#define ID_VIEWLAYERS_MAINOBJ           40075
#define IDM_MOBJ                        40076
#define IDM_SOBJ                        40077
#define ID_VIEW_DISPLAYRTC              40078
#define ID_CONFIG_ADVANCED              40079
#define ID_ADVANCED_ADVANCED            40080
#define ID_ADVANCED                     40081
#define ID_SAVETYPE_FORCEASCURRENT      40082
#define IDC_SAVETYPE_FORCE              40083
#define ID_DISPLAYMETHOD_VSYNC          40084
#define ID_TOOLS_SETFONT                40085
#define ID_CONFIG_SETFONT               40086
#define IDD_FONTCONFIG                  40087
#define ID_MAGNIFICATIONFILTER_HQ4X     40088
#define IDM_RENDER_HQ4X                 40089
#define ID_40090                        40090
#define ID_MAGNIFICATIONFILTER_HQ4X40091 40091
#define ID_FILTRI_HQ4X                  40092
#define ID_40093                        40093
#define IDM_SLOT1                       40097
#define ID_DISPLAYMETHOD_OPENGL         40102
#define IDM_FILE_IMPORT_DB              40103
#define IDM_AUTODETECTSAVETYPE_INTERNAL 40104
#define ID_DISPLAYMETHOD_OPENGL_FILTER  40104
#define IDM_AUTODETECTSAVETYPE_FROMDATABASE 40105
#define ID_DISPLAYMETHOD_FILTER         40106
#define IDC_VIEW_PADTOINTEGER           40107
#define ID_TOOLS_VIEWFSNITRO            40108
#define ID_EXTRACTFILE                  40109
#define ID_CONFIG_LOADROMTYPE           40109
#define ID_EXTRACTALL                   40110
#define ID_LOADTORAM                    40110
#define ID_CLOSE                        40111
#define ID_STREAMFROMDISK               40111
#define ID_FSNITRO_VIEW                 40112
#define IDM_FAQ                         40116
#define IDM_WIKI                        40117
#define ID_MAGNIFICATIONFILTER_2XBRZ    40118
#define IDM_RENDER_2XBRZ                40119
#define ID_MAGNIFICATIONFILTER_3XBRZ    40120
#define ID_MAGNIFICATIONFILTER_4XBRZ    40121
#define ID_MAGNIFICATIONFILTER_5XBRZ    40122
#define IDM_RENDER_3XBRZ                40123
#define IDM_RENDER_4XBRZ                40124
#define IDM_RENDER_5XBRZ                40125
#define IDC_SCR_RATIO_1p0               40143
#define IDC_SCR_RATIO_1p1               40144
#define IDC_SCR_RATIO_1p2               40145
#define IDC_SCR_RATIO_1p3               40146
#define IDC_SCR_RATIO_1p4               40147
#define IDC_SCR_RATIO_1p5               40148
#define IDC_SCR_VCENTER                 40149
#define IDM_FS_MENU                     40150
#define IDM_FS_WINDOW                   40151
#define IDM_FS_HIDE_CURSOR              40152
#define ID_TOOLS_SHOWCONSOLE            40153
#define ID_TOOLS_CONSOLE                40154
#define ID_CONSOLE_ALWAYSONTOP          40155
#define ID_CONSOLE_SHOWCONSOLE          40156
#define IDM_CONSOLE_SHOW                40157
#define IDM_CONSOLE_SHOWHIDE            40158
#define ID_LABEL_HK3b                   44670
#define ID_LABEL_HK3c                   44671
#define ID_LABEL_HK3d                   44672
#define ID_LABEL_HK8b                   44720
#define IDC_LABEL_UP                    50000
#define IDC_LABEL_RIGHT                 50001
#define IDC_LABEL_LEFT                  50002
#define IDC_LABEL_DOWN                  50003
#define IDC_LABEL_A                     50004
#define IDC_LABEL_X                     50005
#define IDC_LABEL_B                     50006
#define IDC_LABEL_Y                     50007
#define IDC_LABEL_L                     50008
#define IDC_LABEL_START                 50009
#define IDC_LABEL_R                     50010
#define IDC_LABEL_SELECT                50011
#define IDC_LABEL_UPLEFT                50012
#define IDC_LABEL_DOWNRIGHT             50013
#define IDC_LABEL_UPRIGHT               50014
#define IDC_LABEL_DOWNLEFT              50015
#define IDC_ALLOWLEFTRIGHT              50016
#define IDC_LABEL_X3                    50017
#define IDC_LABEL_X2                    50018
#define IDC_DEBUG                       50019
#define IDC_UP                          50020
#define IDC_LEFT                        50021
#define IDC_DOWN                        50022
#define IDC_RIGHT                       50023
#define IDC_B                           50024
#define IDC_A                           50025
#define IDC_Y                           50026
#define IDC_X                           50027
#define IDC_START                       50028
#define IDC_SELECT                      50029
#define IDC_L                           50030
#define IDC_R                           50031
#define IDC_UPLEFT                      50032
#define IDC_UPRIGHT                     50033
#define IDC_DWNRIGHT                    50034
#define IDC_DWNLEFT                     50035
#define IDC_LABEL_BLUE                  50036
#define IDC_LID                         50037
#define IDD_INPUTCONFIG                 50038
#define IDC_LABEL_BLUE1                 50039
#define IDC_KILLSTYLUS                  50039
#define IDC_KILLSTYLUSTOP               50039
#define IDC_KILLSTYLUSOFF               50040
#define ID_LABEL_S_0_ALPHA_BLEND        50186
#define ID_LABEL_NDS_DEPTH_CALC         50187
#define ID_LABEL_DEPTH_L_EQUAL_PF       50188
#define IDC_LUASCRIPT_RESERVE_START     58000
#define IDC_LUASCRIPT_RESERVE_END       58099
#define IDD_LUARECENT_RESERVE_START     58100
#define IDD_LUARECENT_RESERVE_END       58199
#define IDC_LUAMENU_RESERVE_START       58200
#define IDC_LUAMENU_RESERVE_END         58399
#define IDC_FRAMEADVANCE                58400
#define IDC_LABEL_HK1                   60001
#define IDC_LABEL_HK2                   60002
#define IDC_LABEL_HK3                   60003
#define IDC_LABEL_HK4                   60004
#define IDC_LABEL_HK5                   60005
#define IDC_LABEL_HK6                   60006
#define IDC_LABEL_HK7                   60007
#define IDC_LABEL_HK8                   60008
#define IDC_LABEL_HK9                   60009
#define IDC_HOTKEY1                     60011
#define IDC_HOTKEY2                     60012
#define IDC_HOTKEY3                     60013
#define IDC_HOTKEY4                     60014
#define IDC_HOTKEY5                     60015
#define IDC_HOTKEY6                     60016
#define IDC_HOTKEY7                     60017
#define IDC_HOTKEY8                     60018
#define IDC_HOTKEY9                     60019
#define IDC_HOTKEY10                    60020
#define IDC_HOTKEY11                    60021
#define IDC_HOTKEY12                    60022
#define IDC_HOTKEY13                    60023
#define IDC_HOTKEY14                    60024
#define IDC_HOTKEY15                    60025
#define IDC_HOTKEY16                    60026
#define IDC_HOTKEY17                    60027
#define IDC_HOTKEY18                    60028
#define IDC_HOTKEY19                    60029
#define IDC_HOTKEY20                    60030
#define IDC_LABEL_HK10                  60031
#define IDC_LABEL_HK11                  60032
#define IDC_LABEL_HK12                  60033
#define IDC_LABEL_HK13                  60034
#define IDC_LABEL_HK14                  60035
#define IDC_LABEL_HK15                  60036
#define IDC_LABEL_HK16                  60037
#define IDC_LABEL_HK17                  60038
#define IDC_LABEL_HK19                  60040
#define IDC_LABEL_HK20                  60041
#define IDC_LABEL_HK18                  60049
#define IDC_HKCOMBO                     60077
#define IDD_KEYCUSTOM                   60078
#define IDM_HOTKEY_CONFIG               60079
#define IDM_RENDER_HQ2XS                60081
#define IDM_RENDER_LQ2X                 60082
#define IDM_RENDER_LQ2XS                60083
#define IDC_SAVETYPE                    64000
#define IDC_AUTOLOADLUA                 64001
#define IDC_TXTHACK                     64002
#define ID_LABEL_TXTHACK1               64003
#define ID_LABEL_TXTHACK2               64004
#define ID_LABEL_MSAA_SAMPLES           64005
#define ID_LABEL_GPU_COLOR_DEPTH        64006
#define ID_LABEL_TEXTURE_SCALING        64007
#define ID_LABEL_SHADOW_POLYGONS        64009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40159
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
