name: desmume-emulator
version: 0.9.13
summary: DeSmuME is a Nintendo DS Emulator
description: |
  An open-source Nintendo DS Emulators.
adopt-info: desmume-emulator
grade: stable
confinement: strict
base: core22
compression: lzo
parts:
  desmume-emulator:
    source: https://github.com/TASEmulators/desmume/archive/refs/tags/release_0_9_13.tar.gz
    plugin: nil
    override-build: |
      sed -i 's|Icon=org.desmume.DeSmuME|Icon=${CRAFT_PART_INSTALL}/usr/share/icons/hicolor/scalable/apps/org.desmume.DeSmuME.svg|g' desmume/src/frontend/posix/gtk/org.desmume.DeSmuME.desktop
      LDFLAGS="" CFLAGS="-O3" CXXFLAGS="-O3" FFLAGS="" FCFLAGS="" DEB_CFLAGS_SET="-O3" DEB_CXXFLAGS_SET="-O3" DEB_FFLAGS_SET="" DEB_FCFLAGS_SET="" DEB_LDFLAGS_SET="" meson setup --prefix=${CRAFT_PART_INSTALL}/usr desmume/src/frontend/posix/build desmume/src/frontend/posix
      LDFLAGS="" CFLAGS="-O3" CXXFLAGS="-O3" FFLAGS="" FCFLAGS="" DEB_CFLAGS_SET="-O3" DEB_CXXFLAGS_SET="-O3" DEB_FFLAGS_SET="" DEB_FCFLAGS_SET="" DEB_LDFLAGS_SET="" ninja -C desmume/src/frontend/posix/build
      LDFLAGS="" CFLAGS="-O3" CXXFLAGS="-O3" FFLAGS="" FCFLAGS="" DEB_CFLAGS_SET="-O3" DEB_CXXFLAGS_SET="-O3" DEB_FFLAGS_SET="" DEB_FCFLAGS_SET="" DEB_LDFLAGS_SET="" ninja install -C desmume/src/frontend/posix/build

    stage-packages:
      - libasound2
      - libc6
      - libcairo2
      - libgcc-s1
      - libgdk-pixbuf-2.0-0
      - libgl1
      - libglib2.0-0
      - libglu1-mesa
      - libgtkglext1
      - libosmesa6
      - libpango-1.0-0
      - libsdl2-2.0-0
      - libsoundtouch1
      - libstdc++6
      - libtinyxml2.6.2v5
      - zlib1g
      - gettext
      - pkg-config
      - git
      - zip
      - libosmesa6
      - libagg2
      - libgtkglext1
      - libsoundtouch1
      - libsdl2-2.0-0
      - libpcap0.8
      - libgtk-3-0
      - libgtk-3-bin
      - libgtk-3-common
    build-packages:
      - g++
      - gcc
      - gettext
      - make
      - cmake
      - nasm
      - pkg-config
      - git
      - zip
      - build-essential
      - intltool
      - libosmesa6-dev
      - libagg2-dev
      - intltool
      - quilt
      - libgtkglext1-dev
      - libtinyxml-dev
      - libsoundtouch-dev
      - dh-autoreconf
      - meson
      - libsdl2-dev
      - libpcap-dev
      - libgtk-3-dev

apps:
  desmume-emulator:
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - opengl
      - joystick
      - raw-usb
      - screen-inhibit-control
      - home
      - removable-media
      - network
      - wayland
      - x11
    command: usr/bin/desmume
    desktop: usr/share/applications/org.desmume.DeSmuME.desktop
    extensions: [gnome]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
