/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef YOPYOP_PRIVATE_H
#define YOPYOP_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.0.7.0"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	7
#define VER_BUILD	0
#define COMPANY_NAME	"yopyop"
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"NDS(tm) emulator"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"DeSmuME"
#define PRODUCT_VERSION	""

#endif /*YOPYOP_PRIVATE_H*/
