# Project: desmume
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = ../main.o ../../arm_instructions.o ../../bios.o ../../cp15.o ../../Disassembler.o ../../GPU.o ../../MMU.o ../../NDSSystem.o ../../thumb_instructions.o ../../armcpu.o ../../debug.o ../../FIFO.o $(RES)
LINKOBJ  = ../main.o ../../arm_instructions.o ../../bios.o ../../cp15.o ../../Disassembler.o ../../GPU.o ../../MMU.o ../../NDSSystem.o ../../thumb_instructions.o ../../armcpu.o ../../debug.o ../../FIFO.o $(RES)
LIBS =  -L"lib" -mwindows -limm32 -lshell32 -lole32 -luuid -lintl -lpangowin32-1.0.dll -latk-1.0.dll -lgdk_pixbuf-2.0.dll -lgdk-win32-2.0.dll -lglib-2.0.dll -lgmodule-2.0.dll -lgobject-2.0.dll -lgthread-2.0.dll -lgtk-win32-2.0.dll -lpango-1.0.dll libpthreadGC2.a libSDL.a  
INCS =  -I"include" 
CXXINCS =  -I"lib/gcc/mingw32/3.4.2/include"  -I"include/c++/3.4.2/backward"  -I"include/c++/3.4.2/mingw32"  -I"include/c++/3.4.2"  -I"include" 
BIN  = desmume.exe
CXXFLAGS = $(CXXINCS) -I"C:\Dev-Cpp\\include\gtk-2.0" -I"C:\Dev-Cpp\\lib\gtk-2.0\include" -I"C:\Dev-Cpp\\include\atk-1.0" -I"C:\Dev-Cpp\\include\pango-1.0" -I"C:\Dev-Cpp\\include\glib-2.0" -I"C:\Dev-Cpp\\include\glib-2.0\glib" -I"C:\Dev-Cpp\\lib\glib-2.0" -I"C:\Dev-Cpp\\lib\glib-2.0\include" -mno-cygwin -mms-bitfields -mconsole  
CFLAGS = $(INCS) -I"C:\Dev-Cpp\\include\gtk-2.0" -I"C:\Dev-Cpp\\lib\gtk-2.0\include" -I"C:\Dev-Cpp\\include\atk-1.0" -I"C:\Dev-Cpp\\include\pango-1.0" -I"C:\Dev-Cpp\\include\glib-2.0" -I"C:\Dev-Cpp\\include\glib-2.0\glib" -I"C:\Dev-Cpp\\lib\glib-2.0" -I"C:\Dev-Cpp\\lib\glib-2.0\include" -mno-cygwin -mms-bitfields  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before desmume.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "desmume.exe" $(LIBS)

../main.o: ../main.cpp
	$(CPP) -c ../main.cpp -o ../main.o $(CXXFLAGS)

../../arm_instructions.o: ../../arm_instructions.cpp
	$(CPP) -c ../../arm_instructions.cpp -o ../../arm_instructions.o $(CXXFLAGS)

../../bios.o: ../../bios.cpp
	$(CPP) -c ../../bios.cpp -o ../../bios.o $(CXXFLAGS)

../../cp15.o: ../../cp15.cpp
	$(CPP) -c ../../cp15.cpp -o ../../cp15.o $(CXXFLAGS)

../../Disassembler.o: ../../Disassembler.cpp
	$(CPP) -c ../../Disassembler.cpp -o ../../Disassembler.o $(CXXFLAGS)

../../GPU.o: ../../GPU.cpp
	$(CPP) -c ../../GPU.cpp -o ../../GPU.o $(CXXFLAGS)

../../MMU.o: ../../MMU.cpp
	$(CPP) -c ../../MMU.cpp -o ../../MMU.o $(CXXFLAGS)

../../NDSSystem.o: ../../NDSSystem.cpp
	$(CPP) -c ../../NDSSystem.cpp -o ../../NDSSystem.o $(CXXFLAGS)

../../thumb_instructions.o: ../../thumb_instructions.cpp
	$(CPP) -c ../../thumb_instructions.cpp -o ../../thumb_instructions.o $(CXXFLAGS)

../../armcpu.o: ../../armcpu.cpp
	$(CPP) -c ../../armcpu.cpp -o ../../armcpu.o $(CXXFLAGS)

../../debug.o: ../../debug.c
	$(CPP) -c ../../debug.c -o ../../debug.o $(CXXFLAGS)

../../FIFO.o: ../../FIFO.cpp
	$(CPP) -c ../../FIFO.cpp -o ../../FIFO.o $(CXXFLAGS)
