#ifndef _FOOBAR2000_H_
#define _FOOBAR2000_H_

#include "../../pfc/pfc.h"

#include "utf8api.h"

#include "service.h"

#include "audio_chunk.h"
#include "componentversion.h"
#include "config.h"
#include "config_var.h"
#include "console.h"
#include "coreversion.h"
#include "cvt_float_to_linear.h"
#include "diskwriter.h"
#include "dsp.h"
#include "dsp_manager.h"
#include "file_info.h"
#include "file_info_helper.h"
#include "initquit.h"
#include "input.h"
#include "input_helpers.h"
#include "menu_item.h"
#include "menu_manager.h"
#include "modeless_dialog.h"
#include "output.h"
#include "output_manager.h"
#include "play_callback.h"
#include "play_control.h"
#include "playable_location.h"
#include "playback_core.h"
#include "playlist.h"
#include "playlist_loader.h"
#include "reader.h"
#include "replaygain.h"
#include "resampler.h"
#include "service_helper.h"
#include "tagread.h"
#include "titleformat.h"
#include "ui.h"
#include "unpack.h"
#include "vis.h"
#include "playlist_switcher.h"
#include "packet_decoder.h"
#include "commandline.h"

#endif //_FOOBAR2000_H_