#!/bin/sh

rm -rf desmume.app
mkdir desmume.app
mkdir desmume.app/MacOS
cp desmume-cli desmume.app/MacOS
cp Info.plist desmume.app
../gtk/dylibbundler -cd -d desmume.app/libs -b -x desmume.app/MacOS/desmume-cli
./fixups
