#!/bin/sh

install_name_tool -change /Library/Frameworks/Cairo.framework/Libraries/libpng12.0.dylib @executable_path/../libs/libpng12.0.dylib desmume.app/libs/Cairo
install_name_tool -change /Library/Frameworks/Cairo.framework/Libraries/libcairo.2.dylib @executable_path/../libs/libcairo.2.dylib desmume.app/libs/Cairo
install_name_tool -change /Library/Frameworks/Gtk.framework/Libraries/libpixman-1.0.dylib @executable_path/../libs/libpixman-1.0.dylib desmume.app/libs/libcairo.2.dylib
install_name_tool -change /Library/Frameworks/Gtk.framework/Libraries/libintl.8.dylib @executable_path/../libs/libintl.8.dylib desmume.app/libs/libgdk-pixbuf-2.0.0.dylib
install_name_tool -change /Library/Frameworks/Gtk.framework/Libraries/libintl.8.dylib @executable_path/../libs/libintl.8.dylib desmume.app/libs/libgdk-quartz-2.0.0.dylib
install_name_tool -change /Library/Frameworks/Gtk.framework/Libraries/libintl.8.dylib @executable_path/../libs/libintl.8.dylib desmume.app/libs/libgtk-quartz-2.0.0.dylib
install_name_tool -change /Library/Frameworks/Gtk.framework/Libraries/libintl.8.dylib @executable_path/../libs/libintl.8.dylib desmume.app/libs/libigemacintegration.0.dylib
