/////////////////////////////////////////////////////////////////////////////
// Name:        x.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     12/12/2009 15:45:31
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 12/12/2009 15:45:31

#ifndef _X_H_
#define _X_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/statline.h"
#include "wx/listctrl.h"
#include "wx/treectrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_X 10000
#define ID_MATERIALINTERPOLATE 10004
#define ID_CHECKBOX1 10008
#define ID_PANEL 10001
#define ID_RADIOBUTTON 10005
#define ID_RADIOBUTTON1 10006
#define ID_RADIOBUTTON2 10007
#define ID_LISTCTRL 10002
#define ID_TREECTRL 10003
#define SYMBOL_WXDLG3DVIEWER_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxDIALOG_NO_PARENT|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_WXDLG3DVIEWER_TITLE _("3D Viewer")
#define SYMBOL_WXDLG3DVIEWER_IDNAME ID_X
#define SYMBOL_WXDLG3DVIEWER_SIZE wxSize(399, 299)
#define SYMBOL_WXDLG3DVIEWER_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * wxdlg3dViewer class declaration
 */

class wxdlg3dViewer: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( wxdlg3dViewer )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxdlg3dViewer();
    wxdlg3dViewer( wxWindow* parent, wxWindowID id = SYMBOL_WXDLG3DVIEWER_IDNAME, const wxString& caption = SYMBOL_WXDLG3DVIEWER_TITLE, const wxPoint& pos = SYMBOL_WXDLG3DVIEWER_POSITION, const wxSize& size = SYMBOL_WXDLG3DVIEWER_SIZE, long style = SYMBOL_WXDLG3DVIEWER_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXDLG3DVIEWER_IDNAME, const wxString& caption = SYMBOL_WXDLG3DVIEWER_TITLE, const wxPoint& pos = SYMBOL_WXDLG3DVIEWER_POSITION, const wxSize& size = SYMBOL_WXDLG3DVIEWER_SIZE, long style = SYMBOL_WXDLG3DVIEWER_STYLE );

    /// Destructor
    ~wxdlg3dViewer();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

	virtual void RepaintPanel() {}
	virtual void _OnPaintPanel( wxPaintEvent& event ) {};

////@begin wxdlg3dViewer event handler declarations

    /// wxEVT_CLOSE_WINDOW event handler for ID_X
    void OnCloseWindow( wxCloseEvent& event );

    /// wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_MATERIALINTERPOLATE
    void OnMaterialInterpolateClick( wxCommandEvent& event );

    /// wxEVT_PAINT event handler for ID_PANEL
    void OnPanelPaint( wxPaintEvent& event );

    /// wxEVT_ERASE_BACKGROUND event handler for ID_PANEL
    void OnPanelEraseBackground( wxEraseEvent& event );

////@end wxdlg3dViewer event handler declarations

////@begin wxdlg3dViewer member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxdlg3dViewer member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxdlg3dViewer member variables
    wxCheckBox* checkMaterialInterpolate;
    wxPanel* panelViewport;
////@end wxdlg3dViewer member variables
};

#endif
    // _X_H_
