name: Build Desmume AppImage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libsdl1.2-dev libgl1-mesa-dev libpng-dev libjpeg-dev libportmidi-dev libportaudio-dev libqt4-dev libasound2-dev libxmu-dev libxi-dev libxxf86vm-dev libgtk2.0-dev libpcap-dev libpcap0.8-dev
      - name: Configure and build Desmume
        run: |
          mkdir build
          cd build
          cmake ..
          make -j`nproc`
      - name: Install linuxdeployqt
        run: |
          wget -O linuxdeployqt "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod +x linuxdeployqt
      - name: Create AppDir
        run: |
          mkdir -p AppDir/usr/bin
          cp build/src/frontend/desmume/AppImageAssistant.AppDir/usr/bin/desmume
      - name: Build AppImage
        run: |
          ./linuxdeployqt AppDir/usr/bin/desmume -appimage
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v2
        with:
          name: Desmume-AppImage
          path: Desmume*.AppImage
