name: Build Desmume AppImage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libsdl1.2-dev libgl1-mesa-dev libpng-dev libjpeg-dev libportmidi-dev libportaudio-dev libqt4-dev libasound2-dev libxmu-dev libxi-dev libxxf86vm-dev libgtk2.0-dev libpcap-dev libpcap0.8-dev
      - name: Configure and build Desmume
        run: |
          mkdir build
          cd build
          cmake ..
          make -j`nproc`
      - name: Create AppImage
        uses: AppImageCrafters/appimage-builder-action@main
        with:
          appimage-name: desmume
          appimage-dir: "build/src/frontend/desmume"
      - uses: actions/upload-artifact@v2
        with:
          name: Desmume-AppImage
          path: desmume*.AppImage
