name: DeSmuME

on:
  - push
  - pull_request

jobs:
  build:
    name: Build DeSmuME (Linux)
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: sudo apt update && sudo apt install meson libsdl2-dev libpcap-dev libgtk-3-dev

      - name: meson
        run: |
          cd desmume/src/frontend/posix/
          meson build

      - name: ninja
        run: ninja -C desmume/src/frontend/posix/build

  build_gtk2:
    name: Build DeSmuME (Linux/GTK+2)
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: sudo apt update && sudo apt install autoconf libglu1-mesa-dev libsdl2-dev libpcap-dev libgtk2.0-dev

      - name: buildit
        run: |
          cd desmume/src/frontend/posix/
          autoreconf -i
          ./configure --prefix=/usr --enable-gdb-stub --enable-wifi
          make -j8
          make DESTDIR=/tmp/DeSmuME install

      - name: Pack artifact
        run: |
          cd /tmp
          tar cJf DeSmuME.tar.xz DeSmuME/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: desmume-linux-gtk2-cli-x86_64
          path: /tmp/DeSmuME.tar.xz

  build_macos:
    name: Build DeSmuME (macOS)
    runs-on: macOS-11

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: xcodebuild
        run: |
          cd desmume/src/frontend/cocoa/
          xcodebuild archive -project "DeSmuME (Latest).xcodeproj" -scheme "DeSmuME (macOS App; Intel64 -- Latest Xcode)" -arch x86_64 -archivePath "$(pwd)/desmume.xcarchive" | xcpretty -c
      
      - name: make zip
        run: |
          cd desmume/src/frontend/cocoa/desmume.xcarchive/Products/Applications/
          7z a DeSmuME.app.zip DeSmuME.app

      - name: Upload artifict
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: desmume/src/frontend/cocoa/desmume.xcarchive/Products/Applications/DeSmuME.app.zip
          if-no-files-found: error 

          
  build_appimage:
    name: Build DeSmuME AppImage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt update && sudo apt install meson libsdl2-dev libpcap-dev libgtk-3-dev libgtk2.0-dev autoconf libglu1-mesa-dev

      - name: Build DeSmuME
        run: |
          cd desmume/src/frontend/posix/
          meson build
          ninja -C build

          # Agregar mensaje de salida para mostrar el archivo ejecutable y su ubicación
          echo "Nombre del archivo ejecutable: desmume"
          echo "Ubicación del archivo ejecutable: $(realpath build/desmume)"

      - name: Install AppImage tool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
          chmod +x appimagetool

      - name: Create AppDir
        run: |
          mkdir -p AppDir/usr/bin
          cp /home/runner/work/desmume/desmume/desmume/src/frontend/posix/build/desmume AppDir/usr/bin/
          cp desmume/src/frontend/posix/gtk2/desmume.desktop AppDir/
          cp desmume/src/frontend/windows/DeSmuME.ico AppDir/
          chmod +x AppDir/AppRun

      - name: Build AppImage
        run: |
          ./appimagetool AppDir
